-- Add mood status columns to profiles
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS mood_emoji TEXT DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS mood_text TEXT DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS mood_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
